### ISSUE TITLE
Can't save datasets with elk extract

### ISSUE THREAD

**Issue by AlexTMallen** [EleutherAI/elk#113]
The `save_to_disk` call doesn't work for elk extract.

`elk extract eleutherAI/gpt-j-6B imdb --max_examples 1000 --num_variants 10 --balance --output ~/elk/saved-embeddings`

produces

```Traceback (most recent call last):                                                                                                    
  File "/home/alexm/.conda/envs/alexm-elk/bin/elk", line 8, in <module>
    sys.exit(run())
  File "/home/alexm/elk/elk/__main__.py", line 55, in run
    extract(args.extraction, args.max_gpus).save_to_disk(args.output)
  File "/home/alexm/.conda/envs/alexm-elk/lib/python3.10/site-packages/datasets/dataset_dict.py", line 1225, in save_to_disk
    dataset.save_to_disk(
  File "/home/alexm/.conda/envs/alexm-elk/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1421, in save_to_disk
    for job_id, done, content in Dataset._save_to_disk_single(**kwargs):
  File "/home/alexm/.conda/envs/alexm-elk/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1458, in _save_to_disk_single
    writer.write_table(pa_table)
  File "/home/alexm/.conda/envs/alexm-elk/lib/python3.10/site-packages/datasets/arrow_writer.py", line 567, in write_table
    pa_table = pa_table.combine_chunks()
  File "pyarrow/table.pxi", line 3315, in pyarrow.lib.Table.combine_chunks
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: concatenation of extension<arrow.py_extension_type<Array3DExtensionType>>```

**Comment by norabelrose** [comment]
what the heck

**Comment by norabelrose** [comment]
seems like a `datasets` bug?

**Comment by norabelrose** [comment]
Also I can't actually reproduce this, it works for me

**Comment by norabelrose** [comment]
Never mind idk what I was doing before but I just reproduced it

**Comment by norabelrose** [comment]
`elk extract` is dead
